# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup sbt
      uses: sbt/setup-sbt@v1
    - name: Setup z3
      uses: pavpanchekha/setup-z3@v0.3.0
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git make autoconf g++ flex bison \
          libfl2 libfl-dev zlib1g zlib1g-dev help2man perl python3 

    - name: Cache Verilator build
      id: cache-verilator
      uses: actions/cache@v3
      with:
        path: ~/.cache/verilator
        key: verilator-stable-v1

    - name: Install Verilator
      if: steps.cache-verilator.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/.cache/verilator
        git clone https://github.com/verilator/verilator ~/.cache/verilator/src
        cd ~/.cache/verilator/src
        git checkout stable
        autoconf
        ./configure --prefix=$HOME/.cache/verilator/install
        make -j$(nproc)
        make install

    - name: Add Verilator to PATH
      run: echo "$HOME/.cache/verilator/install/bin" >> $GITHUB_PATH

    - name: Verify Verilator version
      run: verilator --version

    - name: build simulator
      run: make init
    - name: Run tests
      run: make test

